### ISSUE TITLE
open calendar from apps-tab

### ISSUE THREAD

**Issue by jdsauer** [hpi-swa-teaching/CalDavClient#10]
As a lazy user i want to open the calendar from the apps tab so i dont have to type in the start commando into the workspace after i opened the workspace

**Acceptance Criteria:**

- [x] the calendar can be opened through the apps-tab of squeak

**Comment by jdsauer** [comment]
Maybe a option for categorisation?

**Comment by nilsonbsr** [comment]
As a user I want to be able to change the color of entries in order to highlight my appointments depending on priority.

Acceptance Criteria:
[] A way to open a drop-down menu which contains different colors
[] clicking on a color changes the color of entries

**Comment by Neowolf** [comment]
Estimated time 2
