### ISSUE TITLE
Add appointment

### ISSUE THREAD

**Issue by Matrisch** [hpi-swa-teaching/CalDavClient#14]
As a user I want to add appointments on a certain date with a title to create a daily schedule.

Dependency to "Connection to Google Account".

Acceptance criteria:
- [ ] An "add appointment" button to add an appointment for a certain day in the list.
- [ ] A popup window with a text input field with the heading "Appointment title:" to add the title.
- [ ] An "OK"-Button in the popup window to confirm the input.
- [ ] Added appointments are synced with the google acc after confirming the input.

**Comment by LeonMatthes** [comment]
Why does this depend on the "list of upcoming days"?
I should be able to create new appointments anyways, I would just expect them to be synced to my google account which I authorized in #26 
And doesn't any new appointment need at least a date & time?
