### ISSUE TITLE
get a list of next appointments from external calendar client

### ISSUE THREAD

**Issue by Matrisch** [hpi-swa-teaching/CalDavClient#20]
As a daily sqeak user i want to see upcoming appointments from external calendar (google / sabre) directly in sqeak so I don't have to always open another program.

**Acceptance criteria:**

- [ ] a button with wich you can get the next appointments from google / sabre exists
- [x] the titles of (at least) the next 10 appointments are displayed in the list of upcoming days according to the day they're on.
- [x] the appointments are ordered from near to wide future of the start time

**Comment by rheaSPK** [comment]
Estimated time: 13
