### ISSUE TITLE
Set start time for appointment

### ISSUE THREAD

**Issue by Matrisch** [hpi-swa-teaching/CalDavClient#28]
As a user I want to set the start time for an appointment to know when the appointment starts.

Dependency to "Add appointment".

Acceptance criteria:
- [ ] An input field with the heading "Start time" next to the "Appointment title"-field
- [ ] The possability to add a clocktime in the 24h format in the "Start time" field (for example "16:24")
- [ ] Start time get synced with the google acc  after confirming the input.

**Comment by LeonMatthes** [comment]
What should that input field look like?
What happens if I input something into this field?
