### ISSUE TITLE
New appointement window.

### ISSUE THREAD

**Issue by rheaSPK** [hpi-swa-teaching/CalDavClient#29]
As a user I want to have a window to enter the details for an appointment in order to have an intuitive UI for saving my appointments.

Dependency to "List of upcoming days"

**Acceptance Criteria**
- [x] button `new appointment`
- [x] this opens a new dialog which contains
  - [x] `title` (label + textfield)
  - [ ] `date` (label + textfield)
  - [ ] `start time` (label + textfield)
  - [ ] `endtime` (label + textfield)
  - [x] `ok` Button
- [x] after clicking the 'ok' Button the appointment is visible with its attributes in the list of upcoming days

**Comment by rheaSPK** [comment]
Estimated time: 13

**Comment by Neowolf** [comment]
New estimated time: 2

**Comment by LeonMatthes** [comment]
New objective:
- minimize `add apointment` dialog -> perhaps remove date, start- and endtime. (just start the appointment right now)
- push new appointment to google
- refresh
