### ISSUE TITLE
comfortable way to enter calendar id on first time start up

### ISSUE THREAD

**Issue by Matrisch** [hpi-swa-teaching/CalDavClient#33]
As a new user i want to be asked to enter my calendar id after I connected the calendar app to my google account, so I don't need to find a way to enter it.

Acceptance criteria:

- [x] a dialog promt shows up after connection was successful
- [x] a field to enter my calendar id is within that dialog
- [x] a save button that is also located in that dialog saves the id and closes the dialog

**Comment by Matrisch** [comment]
Estimated effort: 5

**Comment by Neowolf** [comment]
New estimated efford: 3
