### ISSUE TITLE
client key/id is located in the calendar itself

### ISSUE THREAD

**Issue by rheaSPK** [hpi-swa-teaching/CalDavClient#38]
As a non programmer i would like to dont have to enter the client key and client id because i dont unterstand how to navigate to any classes or whatever it is called.

Acceptance Criteria.
- [x] client id and client key is already located in the calendar

**Comment by rheaSPK** [comment]
Neue Userstory: einen synchonized button

**Comment by Neowolf** [comment]
Estimated time: 13

**Comment by Neowolf** [comment]
new estimated time 3
