### ISSUE TITLE
 Delete appointments.

### ISSUE THREAD

**Issue by jdsauer** [hpi-swa-teaching/CalDavClient#8]
As a user I want to be able to delete local calendar entries to remove already added, but actually cancelled appointments to improve the overview of the daily appointments.

Dependency to "New Appointment window".

**Acceptance criteria:**

- [x] "Delete appointment" Button for every local appointment exists
- [x] that Button is located next to the appointment
 - [x] After clicking an appointment's delete-button a dialog opens and you are asked if you are sure to delete the appointment. You can choose between a "Yes" and a "Cancel" button.
  - [x] "Yes" - Button deletes the appointment, "Cancel"- Button closes the dialog, the appointment remains

**Comment by Neowolf** [comment]
Estimated time: 5
